name:                aoc2019
version:             0.1.0.0
github:              "mjedwabn/aoc2019"
license:             BSD3
author:              "Maciej Jedwabny"
maintainer:          "rudykot@gmail.com"
copyright:           "Maciej Jedwabny"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mjedwabn/aoc2019#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
    - HUnit
